
server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /baicells
spring:
  #application_name
  application:
    name: baicells
  #file
  servlet:
    multipart:
        max-file-size: 50Mb
        maxRequestSize: 100Mb
  #datasource
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/baicells
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #durid
    druid:
      initial-size: 1
      max-active: 20
      max-wait: 60000
      min-idle: 1
      max-open-prepared-statements: 20
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
          enabled: true
      stat-view-servlet:
        login-username: admin
        login-password: 123456
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /*.js,/*.gif,/*.jpg,/*.png,/*.css,/*.ico,/druid/*
  freemarker:
    cache: true
    template-loader-path:  classpath:/templates/
    content-type: text/html
    charset: UTF-8
    check-template-location: true
    suffix: .ftl
    enabled: true
    settings:
      number_format: "#"
      date_format: yyyy-MM-dd
      locale: zh_CN
      url_escaping_charset: UTF-8
      whitespace_stripping: true
      template_update_delay: 0



#mybatis
mybatis:
  type-aliases-package: com.baicells.*.entity


#transactional 自定义事务支持
transaction:
   read-only-method-rule-transaction-attributes:
#    transaction-bean-names: 事务管理对应的bean名称 默认 *Service , *ServiceImpl
#    read-only-method-rule-transaction-attributes: 只读事务方法名称规则 默认 get*,count*,find*,query*,select*,list*,*
#    required-method-rule-transaction-attributes: 可传播事务方法名称规则 默认 add*,save*,insert*,update*,delete*,edit*,create*,remove*,exec*


#mapper
#mapper:
#  mappers:
#    -tk.mybatis.mapper.common.base.BaseMapper
#  notEmpty: true
#  identity: MYSQL

#pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


#log
#logging:
#  config: classpath:logback-spring.xml


#project_web web信息设置
project:
  name:
  title: 管理平台
  static_domain: ${server.servlet.context-path}/static/web
  version: 1.0001



