package com.baicells.manager.model.entity;

import tk.mybatis.mapper.annotation.KeySql;

import javax.persistence.*;

@Table(name = "`download`")
public class Download {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column download.id
     *
     * @mbg.generated Sun Aug 05 23:05:38 CST 2018
     */
    @Id
    @KeySql(useGeneratedKeys = true)
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column download.url
     *
     * @mbg.generated Sun Aug 05 23:05:38 CST 2018
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column download.id
     *
     * @return the value of download.id
     *
     * @mbg.generated Sun Aug 05 23:05:38 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column download.id
     *
     * @param id the value for download.id
     *
     * @mbg.generated Sun Aug 05 23:05:38 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column download.url
     *
     * @return the value of download.url
     *
     * @mbg.generated Sun Aug 05 23:05:38 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column download.url
     *
     * @param url the value for download.url
     *
     * @mbg.generated Sun Aug 05 23:05:38 CST 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }
}