package com.baicells.manager.model.entity;

import tk.mybatis.mapper.annotation.KeySql;

import javax.persistence.*;

@Table(name = "`t_product_page_detail_mapping`")
public class ProductPageDetailMapping {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_page_detail_mapping.id
     *
     * @mbggenerated Mon Jul 23 18:04:48 CST 2018
     */
    @Id
    @KeySql(useGeneratedKeys = true)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_page_detail_mapping.product_page_id
     *
     * @mbggenerated Mon Jul 23 18:04:48 CST 2018
     */
    private Integer productPageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_page_detail_mapping.product_detail_id
     *
     * @mbggenerated Mon Jul 23 18:04:48 CST 2018
     */
    private Integer productDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_page_detail_mapping.group_title
     *
     * @mbggenerated Mon Jul 23 18:04:48 CST 2018
     */
    private String groupTitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_page_detail_mapping.id
     *
     * @return the value of t_product_page_detail_mapping.id
     *
     * @mbggenerated Mon Jul 23 18:04:48 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_page_detail_mapping.id
     *
     * @param id the value for t_product_page_detail_mapping.id
     *
     * @mbggenerated Mon Jul 23 18:04:48 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_page_detail_mapping.product_page_id
     *
     * @return the value of t_product_page_detail_mapping.product_page_id
     *
     * @mbggenerated Mon Jul 23 18:04:48 CST 2018
     */
    public Integer getProductPageId() {
        return productPageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_page_detail_mapping.product_page_id
     *
     * @param productPageId the value for t_product_page_detail_mapping.product_page_id
     *
     * @mbggenerated Mon Jul 23 18:04:48 CST 2018
     */
    public void setProductPageId(Integer productPageId) {
        this.productPageId = productPageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_page_detail_mapping.product_detail_id
     *
     * @return the value of t_product_page_detail_mapping.product_detail_id
     *
     * @mbggenerated Mon Jul 23 18:04:48 CST 2018
     */
    public Integer getProductDetailId() {
        return productDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_page_detail_mapping.product_detail_id
     *
     * @param productDetailId the value for t_product_page_detail_mapping.product_detail_id
     *
     * @mbggenerated Mon Jul 23 18:04:48 CST 2018
     */
    public void setProductDetailId(Integer productDetailId) {
        this.productDetailId = productDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_page_detail_mapping.group_title
     *
     * @return the value of t_product_page_detail_mapping.group_title
     *
     * @mbggenerated Mon Jul 23 18:04:48 CST 2018
     */
    public String getGroupTitle() {
        return groupTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_page_detail_mapping.group_title
     *
     * @param groupTitle the value for t_product_page_detail_mapping.group_title
     *
     * @mbggenerated Mon Jul 23 18:04:48 CST 2018
     */
    public void setGroupTitle(String groupTitle) {
        this.groupTitle = groupTitle;
    }
}