package com.baicells.manager.model.entity;

import tk.mybatis.mapper.annotation.KeySql;
import tk.mybatis.mapper.code.IdentityDialect;

import javax.persistence.*;

@Table(name = "`t_product_page_content`")
public class ProductPageContent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_page_content.id
     *
     * @mbggenerated Mon Jul 23 18:04:48 CST 2018
     */
    @Id
    @KeySql(useGeneratedKeys = true)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_page_content.product_page_id
     *
     * @mbggenerated Mon Jul 23 18:04:48 CST 2018
     */
    private Integer productPageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_page_content.content
     *
     * @mbggenerated Mon Jul 23 18:04:48 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_page_content.id
     *
     * @return the value of t_product_page_content.id
     *
     * @mbggenerated Mon Jul 23 18:04:48 CST 2018
     */

    private String title;


    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_page_content.id
     *
     * @param id the value for t_product_page_content.id
     *
     * @mbggenerated Mon Jul 23 18:04:48 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_page_content.product_page_id
     *
     * @return the value of t_product_page_content.product_page_id
     *
     * @mbggenerated Mon Jul 23 18:04:48 CST 2018
     */
    public Integer getProductPageId() {
        return productPageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_page_content.product_page_id
     *
     * @param productPageId the value for t_product_page_content.product_page_id
     *
     * @mbggenerated Mon Jul 23 18:04:48 CST 2018
     */
    public void setProductPageId(Integer productPageId) {
        this.productPageId = productPageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_page_content.content
     *
     * @return the value of t_product_page_content.content
     *
     * @mbggenerated Mon Jul 23 18:04:48 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_page_content.content
     *
     * @param content the value for t_product_page_content.content
     *
     * @mbggenerated Mon Jul 23 18:04:48 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }
}