package com.baicells.manager.model.entity;

import tk.mybatis.mapper.annotation.KeySql;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`t_solution_let_page`")
public class SolutionLetPage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_solution_let_page.id
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    @Id
    @KeySql(useGeneratedKeys = true)
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_solution_let_page.title
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_solution_let_page.portal_pic_url
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    private String portalPicUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_solution_let_page.portal_forward_url
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    private String portalForwardUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_solution_let_page.nav_pic_url
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    private String navPicUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_solution_let_page.bg_pic_url
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    private String bgPicUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_solution_let_page.create_time
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_solution_let_page.update_time
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_solution_let_page.enable
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    private Boolean enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_solution_let_page.content
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_solution_let_page.id
     *
     * @return the value of t_solution_let_page.id
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_solution_let_page.id
     *
     * @param id the value for t_solution_let_page.id
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_solution_let_page.title
     *
     * @return the value of t_solution_let_page.title
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_solution_let_page.title
     *
     * @param title the value for t_solution_let_page.title
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_solution_let_page.portal_pic_url
     *
     * @return the value of t_solution_let_page.portal_pic_url
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    public String getPortalPicUrl() {
        return portalPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_solution_let_page.portal_pic_url
     *
     * @param portalPicUrl the value for t_solution_let_page.portal_pic_url
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    public void setPortalPicUrl(String portalPicUrl) {
        this.portalPicUrl = portalPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_solution_let_page.portal_forward_url
     *
     * @return the value of t_solution_let_page.portal_forward_url
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    public String getPortalForwardUrl() {
        return portalForwardUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_solution_let_page.portal_forward_url
     *
     * @param portalForwardUrl the value for t_solution_let_page.portal_forward_url
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    public void setPortalForwardUrl(String portalForwardUrl) {
        this.portalForwardUrl = portalForwardUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_solution_let_page.nav_pic_url
     *
     * @return the value of t_solution_let_page.nav_pic_url
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    public String getNavPicUrl() {
        return navPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_solution_let_page.nav_pic_url
     *
     * @param navPicUrl the value for t_solution_let_page.nav_pic_url
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    public void setNavPicUrl(String navPicUrl) {
        this.navPicUrl = navPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_solution_let_page.bg_pic_url
     *
     * @return the value of t_solution_let_page.bg_pic_url
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    public String getBgPicUrl() {
        return bgPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_solution_let_page.bg_pic_url
     *
     * @param bgPicUrl the value for t_solution_let_page.bg_pic_url
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    public void setBgPicUrl(String bgPicUrl) {
        this.bgPicUrl = bgPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_solution_let_page.create_time
     *
     * @return the value of t_solution_let_page.create_time
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_solution_let_page.create_time
     *
     * @param createTime the value for t_solution_let_page.create_time
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_solution_let_page.update_time
     *
     * @return the value of t_solution_let_page.update_time
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_solution_let_page.update_time
     *
     * @param updateTime the value for t_solution_let_page.update_time
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_solution_let_page.enable
     *
     * @return the value of t_solution_let_page.enable
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_solution_let_page.enable
     *
     * @param enable the value for t_solution_let_page.enable
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_solution_let_page.content
     *
     * @return the value of t_solution_let_page.content
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_solution_let_page.content
     *
     * @param content the value for t_solution_let_page.content
     *
     * @mbg.generated Mon Jul 30 02:07:31 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }
}