package com.baicells.manager.model.entity;

import tk.mybatis.mapper.annotation.KeySql;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`t_support_download`")
public class SupportDownload {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_support_download.id
     *
     * @mbg.generated Wed Aug 01 23:21:21 CST 2018
     */
    @Id
    @KeySql(useGeneratedKeys = true)
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_support_download.title
     *
     * @mbg.generated Wed Aug 01 23:21:21 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_support_download.url
     *
     * @mbg.generated Wed Aug 01 23:21:21 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_support_download.type
     *
     * @mbg.generated Wed Aug 01 23:21:21 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_support_download.create_time
     *
     * @mbg.generated Wed Aug 01 23:21:21 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_support_download.id
     *
     * @return the value of t_support_download.id
     *
     * @mbg.generated Wed Aug 01 23:21:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_support_download.id
     *
     * @param id the value for t_support_download.id
     *
     * @mbg.generated Wed Aug 01 23:21:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_support_download.title
     *
     * @return the value of t_support_download.title
     *
     * @mbg.generated Wed Aug 01 23:21:21 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_support_download.title
     *
     * @param title the value for t_support_download.title
     *
     * @mbg.generated Wed Aug 01 23:21:21 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_support_download.url
     *
     * @return the value of t_support_download.url
     *
     * @mbg.generated Wed Aug 01 23:21:21 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_support_download.url
     *
     * @param url the value for t_support_download.url
     *
     * @mbg.generated Wed Aug 01 23:21:21 CST 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_support_download.type
     *
     * @return the value of t_support_download.type
     *
     * @mbg.generated Wed Aug 01 23:21:21 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_support_download.type
     *
     * @param type the value for t_support_download.type
     *
     * @mbg.generated Wed Aug 01 23:21:21 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_support_download.create_time
     *
     * @return the value of t_support_download.create_time
     *
     * @mbg.generated Wed Aug 01 23:21:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_support_download.create_time
     *
     * @param createTime the value for t_support_download.create_time
     *
     * @mbg.generated Wed Aug 01 23:21:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}