package com.baicells.manager.model.entity;

import tk.mybatis.mapper.annotation.KeySql;

import javax.persistence.*;

@Table(name = "`t_sys_page_config`")
public class SysPageConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_page_config.id
     *
     * @mbg.generated Sat Aug 04 12:51:28 CST 2018
     */
    @Id
    @KeySql(useGeneratedKeys = true)
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_page_config.solution_5g_nav_desc
     *
     * @mbg.generated Sat Aug 04 12:51:28 CST 2018
     */
    @Column(name = "solution_5g_nav_desc")
    private String solution5gNavDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_page_config.id
     *
     * @return the value of t_sys_page_config.id
     *
     * @mbg.generated Sat Aug 04 12:51:28 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_page_config.id
     *
     * @param id the value for t_sys_page_config.id
     *
     * @mbg.generated Sat Aug 04 12:51:28 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_page_config.solution_5g_nav_desc
     *
     * @return the value of t_sys_page_config.solution_5g_nav_desc
     *
     * @mbg.generated Sat Aug 04 12:51:28 CST 2018
     */
    public String getSolution5gNavDesc() {
        return solution5gNavDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_page_config.solution_5g_nav_desc
     *
     * @param solution5gNavDesc the value for t_sys_page_config.solution_5g_nav_desc
     *
     * @mbg.generated Sat Aug 04 12:51:28 CST 2018
     */
    public void setSolution5gNavDesc(String solution5gNavDesc) {
        this.solution5gNavDesc = solution5gNavDesc;
    }
}