package com.baicells.manager.utils;

import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;

public class LanguageUtil {

    public static Map<String, String> map = new LinkedHashMap<>();


    static {
        map.put("Angola","安哥拉");
        map.put("Afghanistan","阿富汗");
        map.put("Albania","阿尔巴尼亚");
        map.put("Algeria","阿尔及利亚");
        map.put("Andorra","安道尔共和国");
        map.put("Anguilla","安圭拉岛");
        map.put("Antigua and Barbuda","安提瓜和巴布达");
        map.put("Argentina","阿根廷");
        map.put("Armenia","亚美尼亚");
        map.put("Ascension","阿森松");
        map.put("Australia","澳大利亚");
        map.put("Austria","奥地利");
        map.put("Azerbaijan","阿塞拜疆");
        map.put("Bahamas","巴哈马");
        map.put("Bahrain","巴林");
        map.put("Bangladesh","孟加拉国");
        map.put("Barbados","巴巴多斯");
        map.put("Belarus","白俄罗斯");
        map.put("Belgium","比利时");
        map.put("Belize","伯利兹");
        map.put("Benin","贝宁");
        map.put("Bermuda Is.","百慕大群岛");
        map.put("Bolivia","玻利维亚");
        map.put("Botswana","博茨瓦纳");
        map.put("Brazil","巴西");
        map.put("Brunei","文莱");
        map.put("Bulgaria","保加利亚");
        map.put("Burkina-faso","布基纳法索");
        map.put("Burma","缅甸");
        map.put("Burundi","布隆迪");
        map.put("Cameroon","喀麦隆");
        map.put("Canada","加拿大");
        map.put("Cayman Is.","开曼群岛");
        map.put("Central African Republic","中非共和国");
        map.put("Chad","乍得");
        map.put("Chile","智利");
        map.put("China","中国");
        map.put("Colombia","哥伦比亚");
        map.put("Congo","刚果");
        map.put("Cook Is.","库克群岛");
        map.put("Costa Rica","哥斯达黎加");
        map.put("Cuba","古巴");
        map.put("Cyprus","塞浦路斯");
        map.put("Czech Republic","捷克");
        map.put("Denmark","丹麦");
        map.put("Djibouti","吉布提");
        map.put("Dominica Rep.","多米尼加共和国");
        map.put("Ecuador","厄瓜多尔");
        map.put("Egypt","埃及");
        map.put("EI Salvador","萨尔瓦多");
        map.put("Estonia","爱沙尼亚");
        map.put("Ethiopia","埃塞俄比亚");
        map.put("Fiji","斐济");
        map.put("Finland","芬兰");
        map.put("France","法国");
        map.put("French Guiana","法属圭亚那");
        map.put("Gabon","加蓬");
        map.put("Gambia","冈比亚");
        map.put("Georgia","格鲁吉亚");
        map.put("Germany","德国");
        map.put("Ghana","加纳");
        map.put("Gibraltar","直布罗陀");
        map.put("Greece","希腊");
        map.put("Grenada","格林纳达");
        map.put("Guam","关岛");
        map.put("Guatemala","危地马拉");
        map.put("Guinea","几内亚");
        map.put("Guyana","圭亚那");
        map.put("Haiti","海地");
        map.put("Honduras","洪都拉斯");
        map.put("Hongkong","香港");
        map.put("Hungary","匈牙利");
        map.put("Iceland","冰岛");
        map.put("India","印度");
        map.put("Indonesia","印度尼西亚");
        map.put("Iran","伊朗");
        map.put("Iraq","伊拉克");
        map.put("Ireland","爱尔兰");
        map.put("Israel","以色列");
        map.put("Italy","意大利");
        map.put("Ivory Coast","科特迪瓦");
        map.put("Jamaica","牙买加");
        map.put("Japan","日本");
        map.put("Jordan","约旦");
        map.put("Kampuchea (Cambodia)","柬埔寨");
        map.put("Kazakstan","哈萨克斯坦");
        map.put("Kenya","肯尼亚");
        map.put("Korea","韩国");
        map.put("Kuwait","科威特");
        map.put("Kyrgyzstan","吉尔吉斯坦");
        map.put("Laos","老挝");
        map.put("Latvia","拉脱维亚");
        map.put("Lebanon","黎巴嫩");
        map.put("Lesotho","莱索托");
        map.put("Liberia","利比里亚");
        map.put("Libya","利比亚");
        map.put("Liechtenstein","列支敦士登");
        map.put("Lithuania","立陶宛");
        map.put("Luxembourg","卢森堡");
        map.put("Macao","澳门");
        map.put("Madagascar","马达加斯加");
        map.put("Malawi","马拉维");
        map.put("Malaysia","马来西亚");
        map.put("Maldives","马尔代夫");
        map.put("Mali","马里");
        map.put("Malta","马耳他");
        map.put("Mariana Is","马里亚那群岛");
        map.put("Martinique","马提尼克");
        map.put("Mauritius","毛里求斯");
        map.put("Mexico","墨西哥");
        map.put("Moldova Republic of","摩尔多瓦");
        map.put("Monaco","摩纳哥");
        map.put("Mongolia","蒙古");
        map.put("Montserrat Is","蒙特塞拉特岛");
        map.put("Morocco","摩洛哥");
        map.put("Mozambique","莫桑比克");
        map.put("Namibia","纳米比亚");
        map.put("Nauru","瑙鲁");
        map.put("Nepal","尼泊尔");
        map.put("Netheriands Antilles","荷属安的列斯");
        map.put("Netherlands","荷兰");
        map.put("New Zealand","新西兰");
        map.put("Nicaragua","尼加拉瓜");
        map.put("Niger","尼日尔");
        map.put("Nigeria","尼日利亚");
        map.put("North Korea","朝鲜");
        map.put("Norway","挪威");
        map.put("Oman","阿曼");
        map.put("Pakistan","巴基斯坦");
        map.put("Panama","巴拿马");
        map.put("Papua New Cuinea","巴布亚新几内亚");
        map.put("Paraguay","巴拉圭");
        map.put("Peru","秘鲁");
        map.put("Philippines","菲律宾");
        map.put("Poland","波兰");
        map.put("French Polynesia","法属玻利尼西亚");
        map.put("Portugal","葡萄牙");
        map.put("Puerto Rico","波多黎各");
        map.put("Qatar","卡塔尔");
        map.put("Reunion","留尼旺");
        map.put("Romania","罗马尼亚");
        map.put("Russia","俄罗斯");
        map.put("Saint Lueia","圣卢西亚");
        map.put("Saint Vincent","圣文森特岛");
        map.put("Samoa Eastern","东萨摩亚(美)");
        map.put("Samoa Western","西萨摩亚");
        map.put("San Marino","圣马力诺");
        map.put("Sao Tome and Principe","圣多美和普林西比");
        map.put("Saudi Arabia","沙特阿拉伯");
        map.put("Senegal","塞内加尔");
        map.put("Seychelles","塞舌尔");
        map.put("Sierra Leone","塞拉利昂");
        map.put("Singapore","新加坡");
        map.put("Slovakia","斯洛伐克");
        map.put("Slovenia","斯洛文尼亚");
        map.put("Solomon Is","所罗门群岛");
        map.put("Somali","索马里");
        map.put("South Africa","南非");
        map.put("Spain","西班牙");
        map.put("Sri Lanka","斯里兰卡");
        map.put("St.Lucia","圣卢西亚");
        map.put("St.Vincent","圣文森特");
        map.put("Sudan","苏丹");
        map.put("Suriname","苏里南");
        map.put("Swaziland","斯威士兰");
        map.put("Sweden","瑞典");
        map.put("Switzerland","瑞士");
        map.put("Syria","叙利亚");
        map.put("Taiwan","台湾省");
        map.put("Tajikstan","塔吉克斯坦");
        map.put("Tanzania","坦桑尼亚");
        map.put("Thailand","泰国");
        map.put("Togo","多哥");
        map.put("Tonga","汤加");
        map.put("Trinidad and Tobago","特立尼达和多巴哥");
        map.put("Tunisia","突尼斯");
        map.put("Turkey","土耳其");
        map.put("Turkmenistan","土库曼斯坦");
        map.put("Uganda","乌干达");
        map.put("Ukraine","乌克兰");
        map.put("United Arab Emirates","阿拉伯联合酋长国");
        map.put("United Kiongdom","英国");
        map.put("United States of America","美国");
        map.put("Uruguay","乌拉圭");
        map.put("Uzbekistan","乌兹别克斯坦");
        map.put("Venezuela","委内瑞拉");
        map.put("Vietnam","越南");
        map.put("Yemen","也门");
        map.put("Yugoslavia","南斯拉夫");
        map.put("Zimbabwe","津巴布韦");
        map.put("Zaire","扎伊尔");
        map.put("Zambia","赞比亚");
    }


    public static String getLanguage(String key) {

        return map.get(key.toLowerCase());
    }

}
